### ISSUE TITLE
Full text search doesn't work

### ISSUE THREAD

**Issue by sjo00** [eraelpeha/docker-seeddms#1]
I tried your repository and it works well. 
But the full text search from seeddms doesn't work. the indexer lists all documents but doesn't create an index.

There was a message about write protection from the extension directory, but it doesn't exists. so i created it in der the workpath from seeddms: /var/www/seeddms/seeddms-6.0.7/ext

if you please can help me!

**Comment by eraelpeha** [comment]
Hi there,
I can reproduce the issue. Looks like pdftotext is not installed. I will update the repository with the latest version of seeddms as well.

**Comment by eraelpeha** [comment]
Updated repository on github and docker hub.

**Comment by sjo00** [comment]
Great. 

But how i upgrade the docker container with data in it (1)? will the fulltext search then work with the integrated files or are they lost? 

is there a way to get it work on existing container (2)?

**Comment by sjo00** [comment]
Ok, i get it to work. 

First i installed 'xpdf' in the docker container, then i chose 'SQLiteFTS' in the settings for the full text search option (not 'Zend Lucene') and it works all fine.
